services:
  db:
    image: postgres:15-alpine
    container_name: saas_banco_horas_db
    restart: always
    environment:
      POSTGRES_USER: bd_matheuslippe
      POSTGRES_PASSWORD: FHiLVgr9OSm6AtJU5WlDkK4G
      POSTGRES_DB: db_banco_horas
    ports:
      - "5432:5433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: saas_banco_horas_api
    restart: always
    ports:
      - "8080:3000"
    environment:
      DATABASE_URL: postgres://bd_matheuslippe:FHiLVgr9OSm6AtJU5WlDkK4G@db:5432/db_banco_horas
      JWT_SECRET: ${JWT_SECRET:-CHANGE_ME_TO_A_STRONG_RANDOM_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_placeholder}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_placeholder}
      BACK_URL: https://suzanna-unhusbanded-gala.ngrok-free.dev
    depends_on:
      - db

  backup:
    build: ./backup
    container_name: saas_banco_horas_backup
    restart: always
    environment:
      DB_HOST: db
      DB_USER: bd_matheuslippe
      DB_PASSWORD: FHiLVgr9OSm6AtJU5WlDkK4G
      DB_NAME: db_banco_horas
    volumes:
      - ./backups:/backups
    depends_on:
      - db

volumes:
  pg_data:
